"use client";

import { useState } from "react";
import type { ArcSweep, SemanticScale } from "../../components/instruments/scales";
import { ArcMeter, AssemblyPipeline, CapacityRail, DeltaIndicator, DNARadar, DistributionRail, InstrumentFrame, NodeTrack, NumericInstrument, OicOrbitalGauge, RadialGauge, SensorBank, StateBeacon, StatusRing, TelemetryStrip, VerticalPressureGauge } from "../../components/instruments";

const states = ["LIVE", "IDLE", "DEGRADED", "FAULT", "UNAVAILABLE", "INSUFFICIENT_DATA", "NOT_CONFIGURED", "UNMEASURED"] as const;
const riskScale: SemanticScale = { polarity: "HIGH_IS_BAD", zones: [{ from: 0, to: 30, state: "NORMAL" }, { from: 30, to: 50, state: "ELEVATED" }, { from: 50, to: 70, state: "WARNING" }, { from: 70, to: 85, state: "SEVERE" }, { from: 85, to: 100, state: "CRITICAL" }] };
const qualityScale: SemanticScale = { polarity: "HIGH_IS_GOOD", zones: [{ from: 0, to: 35, state: "CRITICAL" }, { from: 35, to: 60, state: "WARNING" }, { from: 60, to: 80, state: "ELEVATED" }, { from: 80, to: 100, state: "NORMAL" }] };
const targetScale: SemanticScale = { polarity: "TARGET_RANGE", zones: [{ from: 0, to: 30, state: "WARNING" }, { from: 30, to: 70, state: "TARGET" }, { from: 70, to: 100, state: "WARNING" }], targetRange: [30, 70] };
const lowBadScale: SemanticScale = { polarity: "LOW_IS_BAD", zones: [{ from: 0, to: 20, state: "CRITICAL" }, { from: 20, to: 40, state: "WARNING" }, { from: 40, to: 65, state: "ELEVATED" }, { from: 65, to: 100, state: "NORMAL" }] };
const dimensions = ["Reasoning", "Retrieval", "Evidence", "Memory", "Verification", "Tools", "Search", "Repair", "Reliability", "Efficiency", "Latency", "Cost", "Stability"].map((label, i) => ({ id: `d${i}`, label, state: "PLANNED" as const }));
const sensors = dimensions.map((item, i) => ({ id: item.id, label: item.label, state: "UNMEASURED" as const, kind: (["RADIAL", "ARC", "RING", "PRESSURE"] as const)[i % 4] }));
const arcs: ArcSweep[] = ["SEMI", "EXTENDED_SEMI", "THREE_QUARTER"];

export default function InstrumentGallery() {
  const [rtl, setRtl] = useState(false);
  const labels = rtl ? { title: "نظام أدوات القياس", demo: "قيم توضيحية فقط", arc: "مقارنة هندسة الأقواس", risk: "مقياس ضغط توضيحي" } : { title: "Instrument Design System", demo: "DEMO VALUES ONLY", arc: "Arc geometry comparison", risk: "Synthetic pressure progression" };
  return <main className="oii-gallery" dir={rtl ? "rtl" : "ltr"} lang={rtl ? "ar" : "en"}>
    <header className="oii-gallery-header"><div><small>OIC / DEVELOPMENT REFERENCE</small><h1>{labels.title}</h1><p>{labels.demo} - Synthetic fixtures are confined to this development gallery.</p></div><button type="button" onClick={() => setRtl(!rtl)}>{rtl ? "LTR / EN" : "RTL / العربية"}</button></header>
    <section><h2>01 / Arc geometry</h2><p>{labels.arc} / {labels.demo}; default candidate EXTENDED_SEMI = 220 degrees.</p><div className="oii-gallery-grid oii-gallery-arcs">{arcs.map((sweep) => <article key={sweep}><h3>{sweep} / DEMO</h3><ArcMeter value={68} min={0} max={100} label={`${sweep} / DEMO`} unit="%" sweep={sweep}/></article>)}<article><h3>RADIAL / DEMO</h3><RadialGauge value={68} min={0} max={100} label="Radial / DEMO" unit="%"/></article></div></section>
    <section><h2>02 / Semantic scale contracts</h2><div className="oii-gallery-grid"><article><h3>{labels.risk} / HIGH_IS_BAD / DEMO</h3><div className="oii-gallery-risk">{[20, 50, 70, 85, 97].map((value) => <div key={value}><small>{value}% / DEMO</small><RadialGauge value={value} min={0} max={100} semanticScale={riskScale} unit="%" label={rtl ? "الضغط" : "Pressure"}/></div>)}</div><div className="oii-gallery-states">{[20,50,70,85,97].map((value) => <VerticalPressureGauge key={value} value={value} min={0} max={100} semanticScale={riskScale} label={`${value}% / DEMO`} size="SM"/>)}</div></article><article><h3>Polarity direction / DEMO</h3><div className="oii-gallery-states"><ArcMeter value={86} semanticScale={qualityScale} label={rtl ? "الموثوقية / HIGH_IS_GOOD" : "Reliability / HIGH_IS_GOOD"}/><ArcMeter value={15} semanticScale={lowBadScale} label="Reserve / LOW_IS_BAD"/><ArcMeter value={55} semanticScale={targetScale} label={rtl ? "نطاق التشغيل / TARGET_RANGE" : "Operating band / TARGET_RANGE"}/><ArcMeter value={55} label="Neutral / no thresholds"/></div></article><article><h3>Neutral without explicit bounds</h3><RadialGauge value={83} min={0} max={100} label="No threshold supplied"/></article></div></section>
    <section><h2>03 / State and dormant reference</h2><div className="oii-gallery-grid"><article><h3>StatusRing and Beacon states</h3><div className="oii-gallery-states">{states.map((state) => <div key={state}><small>{state}</small><StatusRing state={state} label="API" size="SM"/><StateBeacon state={state} label={state} pulse={state === "LIVE" || state === "FAULT"}/></div>)}</div></article><article><h3>RadialGauge states</h3><div className="oii-gallery-states">{states.map((state) => <RadialGauge key={state} value={state === "UNMEASURED" || state === "UNAVAILABLE" || state === "NOT_CONFIGURED" || state === "INSUFFICIENT_DATA" ? undefined : 68} min={0} max={100} unit="%" label={state} state={state} size="SM"/>)}</div></article><article><h3>ArcMeter states</h3><div className="oii-gallery-states">{states.map((state) => <ArcMeter key={state} value={state === "UNMEASURED" || state === "UNAVAILABLE" || state === "NOT_CONFIGURED" || state === "INSUFFICIENT_DATA" ? undefined : 68} min={0} max={100} unit="%" label={state} state={state}/>)}</div></article><article><h3>CapacityRail and pressure states</h3><div className="oii-gallery-states">{states.map((state) => <CapacityRail key={`rail-${state}`} value={state === "UNMEASURED" || state === "UNAVAILABLE" || state === "NOT_CONFIGURED" || state === "INSUFFICIENT_DATA" ? undefined : 68} max={100} label={state} state={state} size="SM"/>)}{states.map((state) => <VerticalPressureGauge key={`pressure-${state}`} value={state === "UNMEASURED" || state === "UNAVAILABLE" || state === "NOT_CONFIGURED" || state === "INSUFFICIENT_DATA" ? undefined : 68} min={0} max={100} label={state} state={state} size="SM"/>)}</div></article><article><h3>Numeric states</h3><div className="oii-gallery-states">{states.map((state) => <NumericInstrument key={state} value={state === "UNMEASURED" || state === "UNAVAILABLE" || state === "NOT_CONFIGURED" || state === "INSUFFICIENT_DATA" ? undefined : 1824} unit="req/min" label={state} state={state} size="SM"/>)}</div></article></div></section>
    <section><h2>04 / Distribution and temporal samples</h2><div className="oii-gallery-grid"><article><h3>Distribution / categorical states</h3><DistributionRail sampleSize={12} label="Health mix / DEMO" categories={[{ key: "HEALTHY", count: 8, state: "HEALTHY" }, { key: "DEGRADED", count: 3, state: "DEGRADED" }, { key: "FAULT", count: 1, state: "FAULT" }]}/></article><article><h3>Telemetry / bounded ordered samples</h3><TelemetryStrip label="DEMO line" samples={[20,34,30,58,50,74,67,90]} min={0} max={100} mode="LINE" source="DEVELOPMENT FIXTURE"/><TelemetryStrip label="DEMO bars" samples={[20,34,30,58,50,74,67,90]} min={0} max={100} mode="BARS" source="DEVELOPMENT FIXTURE"/><TelemetryStrip label="Insufficient history / DEMO" samples={[47]} min={0} max={100}/><TelemetryStrip label="No retained history"/></article><article><h3>Numeric and delta</h3><NumericInstrument value={1824} unit="req/min" label="Throughput / DEMO" source="SYNTHETIC DEMO" state="LIVE"/><DeltaIndicator current={120} previous={100} unit="ms" window="DEMO / 1H"/><DeltaIndicator window="NO BASELINE"/></article></div></section>
    <section><h2>05 / Sensor cells</h2><div className="oii-gallery-grid"><article><h3>OIC-7 unmeasured micro instruments</h3><SensorBank sensors={sensors} columns={6}/></article><article><h3>Composite orbital / bounded demo only</h3><OicOrbitalGauge layers={[{ id: "a", label: "Availability", value: 92, state: "LIVE" }, { id: "b", label: "Pressure", value: 68, state: "DEGRADED" }, { id: "c", label: "Quality", value: 81, state: "LIVE" }]}/><OicOrbitalGauge state="UNMEASURED"/></article></div></section>
    <section><h2>06 / Progression and pipeline</h2><div className="oii-gallery-grid"><article><h3>NodeTrack / progression states / DEMO</h3><NodeTrack nodes={[{ label: "Provider", value: "COMPLETE", state: "HEALTHY" }, { label: "Connection", value: "ACTIVE", state: "LIVE" }, { label: "Catalog", value: "WAITING", state: "IDLE" }, { label: "Unavailable", value: "NO FEED", state: "UNAVAILABLE" }]}/></article><article><h3>Assembly pipeline / DEMO</h3><AssemblyPipeline stages={["Family", "Edition", "Revision", "Variant", "Binding", "Visibility"].map((label, i) => ({ id: label, label, value: i + 1, state: i < 2 ? "LIVE" : i === 2 ? "DEGRADED" : "IDLE" }))}/></article><article><h3>InstrumentFrame / dormant-aware</h3><InstrumentFrame label="Queue pressure / DEMO" state="DEGRADED" source="SYNTHETIC" freshness="DEMO WINDOW"><VerticalPressureGauge value={68} min={0} max={100} semanticScale={riskScale} label="DEMO"/></InstrumentFrame></article></div></section>
    <section><h2>07 / Model DNA</h2><article className="oii-gallery-dna"><h3>Planned dimensions; no score</h3><DNARadar dimensions={dimensions}/><h3>Synthetic measured values / DEMO, never sourced in Overview</h3><DNARadar dimensions={dimensions.map((item, i) => i < 7 ? { ...item, state: "MEASURED" as const, value: [.72,.51,.84,.66,.9,.4,.77][i] } : item)}/></article></section>
    <section><h2>08 / Additional structures</h2><div className="oii-gallery-grid"><article><h3>Capacity overflow / DEMO</h3><CapacityRail value={118} max={100} target={75} label="Quota / DEMO" unit="units" semanticScale={riskScale}/></article><article><h3>Pipeline station count / DEMO</h3><AssemblyPipeline stages={[{ id: "a", label: "Configured", value: 4, state: "HEALTHY" }, { id: "b", label: "Missing", value: 0, state: "UNAVAILABLE" }, { id: "c", label: "Planned", state: "UNMEASURED" }]}/></article></div></section>
    <footer>OIC ONLY - DEVELOPMENT ROUTE - SYNTHETIC VALUES NEVER ENTER PRODUCTION DATA</footer>
  </main>;
}
