"use client";

import { useState } from "react";
import type { FormEvent, ReactNode } from "react";
import type { Locale, Messages, View } from "../../i18n";
import type { Row, Snapshot } from "../../types";
import { entryText } from "../../format";

type Props = {
  view: View; locale: Locale; t: Messages; data: Snapshot | null;
  profiles: Row[]; memories: Row[]; knowledge: Row[]; executions: Row[];
  selectedMemory: Row | null; selectedKnowledge: Row | null; selectedTrace: Row | null; workbenchResult: Row | null;
  load: (resource: "memory" | "knowledge" | "traces") => void;
  inspectMemory: (id: string) => void; inspectKnowledge: (id: string) => void; inspectTrace: (id: string) => void;
  perform: (action: string, values?: Row) => Promise<Row | null>;
};
const rows = (value: unknown): Row[] => Array.isArray(value) ? value.filter((item): item is Row => !!item && typeof item === "object" && !Array.isArray(item)) : [];
const scalar = (value: unknown, fallback = "—") => typeof value === "string" || typeof value === "number" || typeof value === "boolean" ? String(value) : fallback;

function NativeTable({ headers, data }: { headers: string[]; data: ReactNode[][] }) {
  return <div className="table-frame"><table><thead><tr>{headers.map((item) => <th key={item}>{item}</th>)}</tr></thead><tbody>{data.length ? data.map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j}>{cell}</td>)}</tr>) : <tr><td colSpan={headers.length} className="empty-cell">No records found.</td></tr>}</tbody></table></div>;
}

export function IntelligenceCenter(props: Props) {
  const { view, locale, t, data, profiles, memories, knowledge, executions, selectedMemory, selectedKnowledge, selectedTrace, workbenchResult, load, inspectMemory, inspectKnowledge, inspectTrace, perform } = props;
  const [query, setQuery] = useState("");
  const text = (en: string, ar: string) => locale === "ar" ? ar : en;
  const customRevisions: Row[] = profiles.flatMap((profile) => rows(profile.revisions).map((revision) => ({ ...revision, profile })));
  const models = data?.modelFamilies.flatMap((family) => rows(family.editions).filter((edition) => edition.lifecycle === "PRODUCTION").map((edition) => ({ id: edition.publicId, name: edition.displayName }))) ?? [];
  const tenantOptions = data?.runtimeContext?.tenants ?? [];
  const saveKnowledge = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    const dependencyKey = entryText(form.get("dependencySourceKey")).trim(); const dependencyRef = entryText(form.get("dependencySourceRef")).trim();
    void perform("intelligence.knowledge.create", { tenantId: entryText(form.get("tenantId")), sourceKey: entryText(form.get("sourceKey")), sourceRef: entryText(form.get("sourceRef")), title: entryText(form.get("title")), content: entryText(form.get("content")), authority: Number(entryText(form.get("authority")) || 50), sourcePriority: Number(entryText(form.get("sourcePriority")) || 50), ...(dependencyKey && dependencyRef ? { dependsOn: [{ sourceKey: dependencyKey, sourceRef: dependencyRef }] } : {}) });
    event.currentTarget.reset();
  };
  const saveMemory = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    void perform("intelligence.memory.create", { tenantId: entryText(form.get("tenantId")), kind: entryText(form.get("kind")), sensitivity: entryText(form.get("sensitivity")), title: entryText(form.get("title")), content: entryText(form.get("content")), sourceType: entryText(form.get("sourceType")), sourceRef: entryText(form.get("sourceRef")), confidence: Number(entryText(form.get("confidence")) || 50), salience: Number(entryText(form.get("salience")) || 50) });
    event.currentTarget.reset();
  };
  const runWorkbench = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    void perform("intelligence.workbench.run", { model: entryText(form.get("model")), tenantId: entryText(form.get("tenantId")), profileRevisionId: entryText(form.get("profileRevisionId")), prompt: entryText(form.get("prompt")), maxOutputUnits: Number(entryText(form.get("maxOutputUnits")) || 1024) });
  };

  if (view === "knowledge") return <section className="panel-stack">
    <div className="panel"><div className="panel-heading"><div><span className="section-index">OIC / TRUSTED SOURCE REGISTRY</span><h3>{t.knowledge}</h3><p>{text("OIC-owned evidence sources, scoped to this application and its tenant grants.", "مصادر أدلة مملوكة لـ OIC ومقيدة بالتطبيق والمستأجرين المصرح بهم.")}</p></div><button className="button subtle" type="button" onClick={() => load("knowledge")}>{t.refresh}</button></div>
      <form className="form-grid" onSubmit={saveKnowledge}><label>{text("Source key", "مفتاح المصدر")}<input name="sourceKey" required maxLength={128} /></label><label>{text("Source reference", "مرجع المصدر")}<input name="sourceRef" required maxLength={512} /></label><label>{t.displayName}<input name="title" required maxLength={240} /></label><label>{t.tenant}<select name="tenantId"><option value="">{text("Application scope", "نطاق التطبيق")}</option>{tenantOptions.map((item) => <option key={String(item.id)} value={String(item.id)}>{String(item.displayName)}</option>)}</select></label><label>Depends on source key (optional)<input name="dependencySourceKey" maxLength={128} /></label><label>Depends on source reference (optional)<input name="dependencySourceRef" maxLength={512} /></label><label>{text("Authority", "الموثوقية")}<input name="authority" type="number" min={0} max={100} defaultValue={50} /></label><label>{text("Application priority", "أولوية التطبيق")}<input name="sourcePriority" type="number" min={0} max={100} defaultValue={50} /></label><label className="wide-field">{text("Evidence content", "محتوى الدليل")}<textarea name="content" required maxLength={200000} /></label><button className="button primary" type="submit">{text("Register knowledge", "تسجيل المعرفة")}</button></form>
    </div>
    <div className="panel"><label className="filter-box">{t.search}<input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); load("knowledge"); } }} /></label>
      <NativeTable headers={["Title", "Source", "Reference", "Dependencies", "Scope", "Authority", "Priority", "Lifecycle", "Updated", "Actions"]} data={knowledge.filter((item) => !query || JSON.stringify(item).toLowerCase().includes(query.toLowerCase())).map((item) => [scalar(item.title), scalar(item.sourceKey), scalar(item.sourceRef), rows(item.dependsOn).map((dependency) => `${scalar(dependency.sourceKey)} / ${scalar(dependency.sourceRef)}`).join("; ") || "None", item.tenantId ? scalar(item.tenantId) : "APPLICATION", scalar(item.authority), scalar(item.sourcePriority), scalar(item.lifecycle), scalar(item.updatedAt), <div className="button-row" key={String(item.id)}><button className="button subtle" type="button" onClick={() => inspectKnowledge(String(item.id))}>{text("Inspect", "عرض")}</button>{item.lifecycle !== "DISABLED" && item.lifecycle !== "ARCHIVED" && <button className="button subtle" type="button" onClick={() => void perform("intelligence.knowledge.update", { id: item.id, lifecycle: "DISABLED" })}>{text("Disable", "تعطيل")}</button>}{item.lifecycle !== "ARCHIVED" && <button className="button subtle danger-button" type="button" onClick={() => void perform("intelligence.knowledge.update", { id: item.id, lifecycle: "ARCHIVED" })}>{text("Archive", "أرشفة")}</button>}</div>])} />
      {selectedKnowledge && <article className="data-card"><header><strong>{scalar(selectedKnowledge.title)}</strong><small>{scalar(selectedKnowledge.sourceKey)} / {scalar(selectedKnowledge.sourceRef)} / {scalar(selectedKnowledge.lifecycle)}</small></header><p>{scalar(selectedKnowledge.content)}</p><small>Authority {scalar(selectedKnowledge.authority)} / application priority {scalar(selectedKnowledge.sourcePriority)} / embedding {scalar(selectedKnowledge.embeddingModel)} / {scalar(selectedKnowledge.embeddingDimensions)} dimensions / dependencies {rows(selectedKnowledge.dependsOn).map((dependency) => `${scalar(dependency.sourceKey)} / ${scalar(dependency.sourceRef)}`).join("; ") || "None"}</small></article>}
    </div>
  </section>;

  if (view === "memory") return <section className="panel-stack">
    <div className="panel"><div className="panel-heading"><div><span className="section-index">OIC / SCOPED MEMORY</span><h3>{t.memory}</h3><p>{text("Runtime writes require explicit remember intent and profile approval. Sensitive records stay out of retrieval.", "تتطلب الكتابة نية تذكّر صريحة وموافقة الملف. لا تدخل السجلات الحساسة في الاسترجاع.")}</p></div><button className="button subtle" type="button" onClick={() => load("memory")}>{t.refresh}</button></div>
      <form className="form-grid" onSubmit={saveMemory}><label>{text("Memory type", "نوع الذاكرة")}<select name="kind"><option>SEMANTIC</option><option>EPISODIC</option><option>APPLICATION</option><option>PROCEDURAL</option></select></label><label>{text("Sensitivity", "الحساسية")}<select name="sensitivity"><option>INTERNAL</option><option>PUBLIC</option><option>SENSITIVE</option><option>RESTRICTED</option></select></label><label>{t.displayName}<input name="title" required maxLength={240} /></label><label>{text("Source type", "نوع المصدر")}<input name="sourceType" defaultValue="operator-reviewed" required maxLength={128} /></label><label>{t.tenant}<select name="tenantId"><option value="">{text("Application scope", "نطاق التطبيق")}</option>{tenantOptions.map((item) => <option key={String(item.id)} value={String(item.id)}>{String(item.displayName)}</option>)}</select></label><label>{text("Confidence", "الثقة")}<input name="confidence" type="number" min={0} max={100} defaultValue={50} /></label><label>{text("Salience", "الأهمية")}<input name="salience" type="number" min={0} max={100} defaultValue={50} /></label><label className="wide-field">{text("Memory content", "محتوى الذاكرة")}<textarea name="content" required maxLength={20000} /></label><button className="button primary" type="submit">{text("Add reviewed memory", "إضافة ذاكرة مراجعة")}</button></form>
    </div>
    <div className="panel"><label className="filter-box">{t.search}<input value={query} onChange={(event) => setQuery(event.target.value)} /></label><NativeTable headers={["Title", "Type", "Scope", "Source", "Confidence", "Freshness", "Lifecycle", "Inspect"]} data={memories.filter((item) => !query || JSON.stringify(item).toLowerCase().includes(query.toLowerCase())).map((item) => [scalar(item.title), scalar(item.kind), item.tenantId ? scalar(item.tenantId) : "APPLICATION", `${scalar(item.sourceType)} / ${scalar(item.sourceRef)}`, scalar(item.confidence), scalar(item.lastConfirmedAt ?? item.updatedAt), scalar(item.lifecycle), <div className="button-row" key={String(item.id)}><button className="button subtle" type="button" onClick={() => inspectMemory(String(item.id))}>{text("Inspect", "عرض")}</button>{item.lifecycle !== "ARCHIVED" && <button className="button subtle danger-button" type="button" onClick={() => void perform("intelligence.memory.lifecycle", { id: item.id, lifecycle: "ARCHIVED" })}>{text("Archive", "أرشفة")}</button>}</div>])} />
      {selectedMemory && <article className="data-card"><header><strong>{scalar(selectedMemory.title)}</strong><small>{scalar(selectedMemory.kind)} · {scalar(selectedMemory.lifecycle)} · confidence {scalar(selectedMemory.confidence)}</small></header><p>{scalar(selectedMemory.content)}</p><small>{text("Provenance", "المصدر")}: {scalar(selectedMemory.sourceType)} · {scalar(selectedMemory.sourceRef)} · valid until {scalar(selectedMemory.validUntil)}</small></article>}
      <h3>{text("Selected in recent executions", "المحدد في عمليات التنفيذ الأخيرة")}</h3><NativeTable headers={["Trace", "Memory decisions"]} data={executions.map((item) => { const summary = item.summary && typeof item.summary === "object" ? item.summary as Row : {}; const selected = rows(summary.memorySelection); return [scalar(item.traceId), selected.map((entry) => `${scalar(entry.kind)} · ${scalar(entry.reason)} · ${scalar(entry.score)}`).join("; ") || "No memory selected"]; })} />
    </div>
  </section>;

  if (view === "workbench") return <section className="panel-stack">
    <div className="panel"><div className="panel-heading"><div><span className="section-index">SAME MODEL / SAME CONTEXT</span><h3>{t.workbench}</h3><p>{text("Runs a bounded baseline and the selected profile through the OIC runtime executor. Compare evidence and cost without declaring a subjective winner.", "يشغّل خط أساس محدوداً والملف المحدد عبر منفذ OIC نفسه للمقارنة الموضوعية في الأدلة والتكلفة.")}</p></div></div>
      <form className="form-grid" onSubmit={runWorkbench}><label>{text("Oi Model", "نموذج Oi")}<select name="model" required>{models.map((model) => <option key={String(model.id)} value={String(model.id)}>{String(model.name)} · {String(model.id)}</option>)}</select></label><label>{text("Intelligence profile revision", "إصدار ملف الذكاء")}<select name="profileRevisionId" required>{customRevisions.map((revision) => <option key={String(revision.id)} value={String(revision.id)}>{String((revision.profile as Row).profileKey)} r{scalar(revision.revision)}</option>)}</select></label><label>{t.tenant}<select name="tenantId"><option value="">{text("Application scope", "نطاق التطبيق")}</option>{tenantOptions.map((item) => <option key={String(item.id)} value={String(item.id)}>{String(item.displayName)}</option>)}</select></label><label>{text("Max output tokens", "حد رموز الإخراج")}<input type="number" name="maxOutputUnits" min={1} max={8192} defaultValue={1024} /></label><label className="wide-field">{text("Task / prompt", "المهمة / الطلب")}<textarea name="prompt" required maxLength={12000} /></label><button className="button primary" type="submit">{text("Run baseline + OIC", "تشغيل خط الأساس و OIC")}</button></form>
    </div>
    {workbenchResult && <div className="split-panels workbench-results">{(["baseline", "augmented"] as const).map((key) => { const run = workbenchResult[key] && typeof workbenchResult[key] === "object" ? workbenchResult[key] as Row : {}; const execution = run.execution && typeof run.execution === "object" ? run.execution as Row : {}; const summary = execution.summary && typeof execution.summary === "object" ? execution.summary as Row : {}; return <article className="panel" key={key}><span className="section-index">{key === "baseline" ? "BASELINE" : `OIC / ${scalar((workbenchResult.requestedProfile as Row | undefined)?.profileKey)}`}</span><p className="workbench-output">{scalar(run.outputText)}</p><div className="runtime-correlation"><span>Duration <b>{scalar(run.durationMs)} ms</b></span><span>Calls <b>{scalar(execution.providerCallCount)}</b></span><span>Retrieval <b>{scalar(execution.retrievalQueryCount)}</b></span><span>Memory reads <b>{scalar(execution.memoryLookupCount)}</b></span><span>Candidates <b>{scalar(summary.candidateCount)}</b></span><span>Verification <b>{scalar(execution.verificationStatus)}</b></span><span>Context estimate <b>{scalar(execution.contextTokens)}</b></span><span>Input / output tokens <b>{scalar(execution.inputTokens)} / {scalar(execution.outputTokens)}</b></span><span>Stop <b>{scalar(summary.stopReason)}</b></span></div><button className="button subtle" type="button" onClick={() => inspectTrace(String(run.traceId))}>{text("Inspect trace", "فحص الأثر")}</button></article>; })}</div>}
    {selectedTrace && <TracePanel trace={selectedTrace} />}
  </section>;

  if (view === "traces") return <section className="panel-stack"><div className="panel"><div className="panel-heading"><div><span className="section-index">TRACE / SAFE STAGE DATA</span><h3>{t.traces}</h3></div><button className="button subtle" type="button" onClick={() => load("traces")}>{t.refresh}</button></div><NativeTable headers={["Trace", "Model", "Profile revision", "Task", "Strategy", "Stages", "Calls", "Queries", "Memory", "Verification", "Open"]} data={executions.map((item) => [scalar(item.traceId), scalar(item.modelId), scalar(item.profileRevisionId ?? "FAST"), scalar(item.taskType), scalar(item.strategy), scalar(item.stageCount), scalar(item.providerCallCount), scalar(item.retrievalQueryCount), scalar(item.memoryLookupCount), scalar(item.verificationStatus), <button key={String(item.id)} className="button subtle" type="button" onClick={() => inspectTrace(String(item.traceId))}>{text("Inspect", "عرض")}</button>])} /></div>{selectedTrace && <TracePanel trace={selectedTrace} />}</section>;

  return null;
}

function TracePanel({ trace }: { trace: Row }) {
  const stages = rows(trace.stages);
  const details = trace.summary && typeof trace.summary === "object" ? trace.summary as Row : {};
  const effective = details.effectiveProfile && typeof details.effectiveProfile === "object" ? details.effectiveProfile as Row : {};
  const intensity = effective.intensity && typeof effective.intensity === "object" ? effective.intensity as Row : {};
  const budgets = effective.budgets && typeof effective.budgets === "object" ? effective.budgets as Row : {};
  const kernel = details.cognitiveKernel && typeof details.cognitiveKernel === "object" ? details.cognitiveKernel as Row : {};
  const problem = details.problemModel && typeof details.problemModel === "object" ? details.problemModel as Row : {};
  const signature = details.cognitiveSignature && typeof details.cognitiveSignature === "object" ? details.cognitiveSignature as Row : {};
  const memoryPlan = details.memoryPlan && typeof details.memoryPlan === "object" ? details.memoryPlan as Row : {};
  const epistemic = details.epistemicState && typeof details.epistemicState === "object" ? details.epistemicState as Row : {};
  const evidenceGraph = details.evidenceGraph && typeof details.evidenceGraph === "object" ? details.evidenceGraph as Row : {};
  const graphSummary = evidenceGraph.summary && typeof evidenceGraph.summary === "object" ? evidenceGraph.summary as Row : {};
  const evidenceCoverage = details.evidenceCoverage && typeof details.evidenceCoverage === "object" ? details.evidenceCoverage as Row : {};
  const coverageSummary = evidenceCoverage.summary && typeof evidenceCoverage.summary === "object" ? evidenceCoverage.summary as Row : {};
  const memoryUtility = details.memoryUtility && typeof details.memoryUtility === "object" ? details.memoryUtility as Row : {};
  const memoryFusion = details.memoryFusion && typeof details.memoryFusion === "object" ? details.memoryFusion as Row : {};
  const hypotheses = rows(details.hypotheses);
  const search = details.cognitiveSearch && typeof details.cognitiveSearch === "object" ? details.cognitiveSearch as Row : details.candidateSearch && typeof details.candidateSearch === "object" ? details.candidateSearch as Row : {};
  const diversity = details.candidateDiversity && typeof details.candidateDiversity === "object" ? details.candidateDiversity as Row : {};
  const comparison = details.candidateComparison && typeof details.candidateComparison === "object" ? details.candidateComparison as Row : {};
  const critic = details.critic && typeof details.critic === "object" ? details.critic as Row : {};
  const usage = details.usageAccounting && typeof details.usageAccounting === "object" ? details.usageAccounting as Row : {};
  const scalarFields = (value: Row) => Object.entries(value).filter(([, item]) => item === null || ["string", "number", "boolean"].includes(typeof item));
  const statuses = (value: unknown) => rows(value).reduce<Record<string, number>>((counts, item) => { const key = scalar(item.status ?? item.state ?? item.decision ?? item.type, "unclassified"); counts[key] = (counts[key] ?? 0) + 1; return counts; }, {});
  const toolStages = stages.filter((stage) => String(stage.stageType).includes("TOOL"));
  const revisionStages = stages.filter((stage) => stage.stageType === "REVISION");
  const cognitiveActions = rows(kernel.actions);
  return <article className="panel"><div className="panel-heading"><div><span className="section-index">{scalar(trace.traceId)}</span><h3>{scalar(trace.taskType)} / {scalar(trace.strategy)}</h3><p>{scalar(trace.uncertainty)} / stop {scalar(details.stopReason)}</p></div></div>
    {Object.keys(effective).length > 0 && <div className="runtime-context-row"><b>Effective profile: {scalar(effective.requestedProfileKey)} r{scalar(effective.revision)} / resolved {scalar(effective.resolvedRevisionId)}</b><span>Task {scalar(effective.taskType)} / strategy {scalar(effective.strategy)} / model capabilities {Array.isArray(effective.modelCapabilities) ? effective.modelCapabilities.map(String).join(", ") : "unknown"}</span><span>Intensity: {Object.entries(intensity).map(([key, value]) => `${key} ${scalar(value)}`).join(" / ")}</span><span>Budgets: {Object.entries(budgets).map(([key, value]) => `${key} ${scalar(value)}`).join(" / ")}</span><span>Capability adjustments: {Array.isArray(effective.capabilityAdjustments) && effective.capabilityAdjustments.length ? effective.capabilityAdjustments.map(String).join(", ") : "none"}</span></div>}
    {(Object.keys(kernel).length > 0 || Object.keys(problem).length > 0 || Object.keys(epistemic).length > 0) && <div className="runtime-context-row"><b>Problem model / epistemic state</b><span>Cognitive depth {scalar(kernel.depth)} / {scalar(problem.taskType)} / {scalar(problem.goalCount)} goals / {scalar(problem.constraintCount)} constraints / ambiguity {scalar(problem.ambiguity)} / hallucination risk {scalar(problem.hallucinationRisk)}</span><span>Completion conditions: {Array.isArray(problem.completionConditions) ? problem.completionConditions.map(String).join(", ") : "none"}</span><span>Epistemic coverage {scalar(epistemic.coverage)} / unresolved {scalar(epistemic.unresolvedCount, "0")} / missing evidence {scalar(epistemic.missingEvidenceCount, "0")} / facts {rows(epistemic.facts).length}</span><span>Signature: {scalar(signature.taskClass)} / retrieval {scalar(signature.retrievalMode)} / candidates {scalar(signature.candidateCount)} / backtracks {scalar(signature.backtracks)}</span></div>}
    {Object.keys(memoryPlan).length > 0 && <div className="runtime-context-row"><b>Memory plan: {Array.isArray(memoryPlan.kinds) && memoryPlan.kinds.length ? memoryPlan.kinds.map(String).join(", ") : "no category selected"}</b><span>{Array.isArray(memoryPlan.reasons) ? memoryPlan.reasons.map(String).join("; ") : "No plan reason"}</span></div>}
    {(Object.keys(memoryUtility).length > 0 || Object.keys(memoryFusion).length > 0 || rows(details.memorySelection).length > 0 || Object.keys(memoryPlan).length > 0) && <div className="runtime-context-row"><b>Memory activity</b><span>Selected {rows(details.memorySelection).length} / fusion decisions {rows(memoryFusion.decisions).length} / relationships {rows(memoryFusion.relationships).length}</span><span>{scalarFields(memoryUtility).map(([key, value]) => `${key} ${scalar(value)}`).join(" / ") || "No utility outcome recorded"}</span></div>}
    {(Object.keys(evidenceCoverage).length > 0 || Object.keys(evidenceGraph).length > 0) && <div className="runtime-context-row"><b>Retrieval / Evidence Graph</b><span>Coverage: {scalarFields(coverageSummary).map(([key, value]) => `${key} ${scalar(value)}`).join(" / ") || "no coverage summary"}</span><span>Graph: {scalarFields(graphSummary).map(([key, value]) => `${key} ${scalar(value)}`).join(" / ") || `nodes ${rows(evidenceGraph.nodes).length} / edges ${rows(evidenceGraph.edges).length} / conflicts ${rows(evidenceGraph.conflicts).length}`}</span><span>Evidence gaps {rows(evidenceCoverage.items).filter((item) => item.status !== "COVERED").length} / next gap {scalar(evidenceCoverage.nextGap, "none")}</span></div>}
    {(hypotheses.length > 0 || Object.keys(search).length > 0 || Object.keys(diversity).length > 0 || Object.keys(comparison).length > 0) && <div className="runtime-context-row"><b>Hypotheses / bounded search / candidates</b><span>Hypothesis states: {Object.entries(statuses(hypotheses)).map(([key, value]) => `${key} ${value}`).join(" / ") || "none"}</span><span>Search: {scalarFields(search).map(([key, value]) => `${key} ${scalar(value)}`).join(" / ") || "no search summary"}</span><span>Diversity: {scalarFields(diversity).map(([key, value]) => `${key} ${scalar(value)}`).join(" / ") || `candidates ${scalar(details.candidateCount, "1")}`}</span><span>Comparison: {scalarFields(comparison).map(([key, value]) => `${key} ${scalar(value)}`).join(" / ") || "no disagreement comparison"}</span></div>}
    {(Object.keys(critic).length > 0 || toolStages.length > 0 || revisionStages.length > 0) && <div className="runtime-context-row"><b>Tools / critic / repair</b><span>Tool stages {toolStages.length} / tool calls {scalar(details.toolCalls, "0")}</span><span>Critic: {scalarFields(critic).map(([key, value]) => `${key} ${scalar(value)}`).join(" / ") || "no critic findings"}</span><span>Verifier {scalar(trace.verificationStatus)} / verification rounds {scalar(details.verificationPasses, "0")} / revisions {revisionStages.length} / backtracks {scalar(signature.backtracks, "0")}</span></div>}
    <div className="runtime-context-row"><b>Resource accounting</b><span>Provider calls {scalar(trace.providerCallCount)} / retrieval {scalar(trace.retrievalQueryCount)} / memory reads {scalar(trace.memoryLookupCount)} / tool calls {scalar(details.toolCalls, "0")}</span><span>Cache hits {scalar(details.cacheHits, "0")} / misses {scalar(details.cacheMisses, "0")} / candidates {scalar(details.candidateCount, "1")} / duration {scalar(details.durationMs)} ms</span><span>Input / output tokens {scalar(usage.inputTokens, scalar(trace.inputTokens))} / {scalar(usage.outputTokens, scalar(trace.outputTokens))} / stop {scalar(details.stopReason)}</span></div>
    {cognitiveActions.length > 0 && <NativeTable headers={["#", "Controller action", "Strategy", "Depth", "Value of compute", "Reason"]} data={cognitiveActions.map((action) => [scalar(action.stageIndex), scalar(action.action), scalar(action.strategy), scalar(action.depth), scalar(action.valueOfCompute ?? "—"), scalar(action.reason)])} />}
    <NativeTable headers={["#", "Stage", "Strategy", "Duration", "Status", "Decision metadata"]} data={stages.map((stage) => [scalar(stage.stageIndex), scalar(stage.stageType), scalar(stage.strategy), `${scalar(stage.durationMs)} ms`, scalar(stage.status), JSON.stringify(stage.metadata ?? {})])} /></article>;
}
