export const AI_PROVIDER_ADAPTERS = Symbol("AI_PROVIDER_ADAPTERS");
export const AI_PROVIDER_REGISTRY = Symbol("AI_PROVIDER_REGISTRY");
export const AI_PROVIDER_FACTORY = Symbol("AI_PROVIDER_FACTORY");
export const AI_ROUTING_SERVICE = Symbol("AI_ROUTING_SERVICE");
export const AI_INVOCATION_SERVICE = Symbol("AI_INVOCATION_SERVICE");
