/* eslint-disable @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-explicit-any, @typescript-eslint/no-unsafe-return, @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-argument */
import { BadRequestException, NotFoundException } from "@nestjs/common";
import { StreamStateMachine } from "./stream-state-machine";
import { StreamingRuntimeRepository } from "./streaming-runtime.repository";
import { StreamingRuntimeService } from "./streaming-runtime.service";

describe("Streaming Runtime",()=>{
 it("enforces strict lifecycle transitions",()=>{const states=new StreamStateMachine();expect(()=>states.assert("PENDING","CONNECTING")).not.toThrow();expect(()=>states.assert("COMPLETED","STREAMING")).toThrow(BadRequestException);expect(()=>states.assert("STREAMING","COMPLETED")).not.toThrow();});
 const create=()=>{const session={id:"session",status:"PENDING",stateVersion:0,startedAt:new Date(),createdAt:new Date(),metric:{},snapshots:[]};const tx:any={streamSession:{create:jest.fn().mockResolvedValue(session),findFirst:jest.fn().mockResolvedValue(session),update:jest.fn(),updateMany:jest.fn().mockResolvedValue({count:1}),findUniqueOrThrow:jest.fn().mockResolvedValue({...session,status:"COMPLETED",stateVersion:1,usageStatus:"UNKNOWN"})},streamChunk:{create:jest.fn().mockResolvedValue({id:"chunk",sequence:1,content:"hello"}),findFirst:jest.fn().mockResolvedValue({sequence:0,createdAt:new Date()})},streamMetric:{update:jest.fn()},streamDiagnostic:{create:jest.fn()},auditLog:{create:jest.fn()}};const prisma:any={$transaction:jest.fn((x:any)=>typeof x==="function"?x(tx):Promise.resolve([[],0])),streamSession:{findFirst:jest.fn().mockResolvedValue(session),findMany:jest.fn(),count:jest.fn()},streamSnapshot:{findFirst:jest.fn().mockResolvedValue({id:"snapshot",snapshotHash:"h",checksum:"c"})}};return{repository:new StreamingRuntimeRepository(prisma,new StreamStateMachine()),prisma,tx};};
 it("creates immutable sessions, metrics, snapshots and audit",async()=>{const {repository,tx}=create();await repository.create("w","a",{providerId:"11111111-1111-4111-8111-111111111111",modelId:"22222222-2222-4222-8222-222222222222",requestHash:"a".repeat(64)});expect(tx.streamSession.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({metric:{create:{}},snapshots:expect.any(Object)})}));expect(tx.auditLog.create).toHaveBeenCalled();});
 it("uses optimistic transitions and persists diagnostics",async()=>{const {repository,tx}=create();await repository.transition("w","a","session","CONNECTING",0,{code:"TRANSPORT",message:"connected"});expect(tx.streamSession.updateMany).toHaveBeenCalledWith(expect.objectContaining({where:{id:"session",workspaceId:"w",stateVersion:0,status:"PENDING"}}));expect(tx.streamDiagnostic.create).toHaveBeenCalled();});
 it("persists immutable ordered chunks and metrics",async()=>{const {repository,tx}=create();tx.streamSession.findFirst.mockResolvedValue({id:"session",status:"STREAMING",startedAt:new Date(),firstTokenAt:null,metric:{chunkCount:0}});tx.streamSession.update=jest.fn();await repository.appendChunk("w","a","session",{sequence:0,content:"hello",role:"assistant"});expect(tx.streamChunk.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({sequence:0,content:"hello"})}));expect(tx.streamMetric.update).toHaveBeenCalled();});
 it("persists final response, UNKNOWN usage, pricing, timestamps and completion audits",async()=>{const {repository,tx}=create();tx.streamSession.findFirst.mockResolvedValue({id:"session",workspaceId:"w",status:"STREAMING",stateVersion:2,startedAt:new Date(),metric:{},snapshots:[]});await repository.complete("w","a","session",2,{invocationId:"invocation",responseContent:"hello",usage:null,cost:null,pricing:{inputCostPerMillion:"1.000000",outputCostPerMillion:"2.000000",currency:"USD"},providerCompletedAt:new Date()});expect(tx.streamSession.updateMany).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({usageStatus:"UNKNOWN",responseContent:"hello",inputTokens:undefined,totalCost:undefined})}));expect(tx.auditLog.create).toHaveBeenCalledTimes(3);});
 it("prevents duplicate completion without creating duplicate final records",async()=>{const {repository,tx}=create();tx.streamSession.findFirst.mockResolvedValue({id:"session",status:"COMPLETED",stateVersion:3});const result=await repository.complete("w","a","session",2,{invocationId:"invocation",responseContent:"hello",usage:null,cost:null,pricing:{inputCostPerMillion:"1.000000",outputCostPerMillion:"2.000000",currency:"USD"},providerCompletedAt:new Date()});expect(result.status).toBe("COMPLETED");expect(tx.streamSession.updateMany).not.toHaveBeenCalled();});
 it("isolates pagination and snapshot comparison",async()=>{const {repository,prisma}=create();await repository.list("w",{page:2,limit:10,status:"PENDING"});expect(prisma.streamSession.findMany).toHaveBeenCalledWith(expect.objectContaining({skip:10,take:10}));await expect(repository.compare("w","left","right")).rejects.toBeInstanceOf(NotFoundException);});
 it("coordinates events, chunks and cancellation",async()=>{const repository:any={create:jest.fn().mockResolvedValue({id:"s",stateVersion:0}),appendChunk:jest.fn().mockResolvedValue({sequence:1}),get:jest.fn().mockResolvedValue({stateVersion:1,status:"STREAMING"}),transition:jest.fn().mockResolvedValue({stateVersion:2}),list:jest.fn(),diagnostics:jest.fn(),metrics:jest.fn(),compare:jest.fn()};const service=new StreamingRuntimeService(repository);await service.create("w","a",{} as never);const events:any[]=[];service.observe("s").subscribe(v=>events.push(v));await service.append("w","a","s",{sequence:1,content:"x"});await service.cancel("w","a","s",{reason:"stop"});expect(events.map(x=>x.event)).toEqual(["started","chunk","cancelled"]);});
});
