"use client";
import { useEffect,useState,type FormEvent,type ReactNode } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ApiError } from "@responix/api-client";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { Badge,Button,Card,CardContent,CardDescription,CardHeader,CardTitle,ErrorFallback,Input,Label,PageSkeleton,Textarea } from "@responix/ui";
import { usePlatformBootstrap } from "../../platform";
import { clonePrompt,createPrompt,getPrompt,listCategories,listTags,promptQueryRoot,publishPrompt,updatePrompt,type PromptRecord,type PromptVariable,type PromptWriteInput } from "./prompt-api";

type FormState={name:string;slug:string;description:string;categoryId:string;tagIds:string[];draft:Record<string,unknown>;variables:string;metadata:string;changeSummary:string};
const empty:FormState={name:"",slug:"",description:"",categoryId:"",tagIds:[],draft:{sections:{systemPrompt:"",developerPrompt:"",userPrompt:""}},variables:"[]",metadata:"{}",changeSummary:""};
const slugify=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,160);
const asRecord=(value:unknown):Record<string,unknown>=>value!==null&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};
const firstString=(...values:unknown[])=>values.find((value):value is string=>typeof value==="string")??"";
const normalizeDraft=(draft:Record<string,unknown>)=>{const sections=asRecord(draft.sections);return {...draft,sections:{...sections,systemPrompt:firstString(sections.systemPrompt,draft.systemPrompt,draft.system_prompt),developerPrompt:firstString(sections.developerPrompt,draft.developerPrompt,draft.developer_prompt),userPrompt:firstString(sections.userPrompt,draft.userPrompt,draft.user_prompt,draft.content,draft.template)}}};
const sectionValue=(draft:Record<string,unknown>,key:"systemPrompt"|"developerPrompt"|"userPrompt")=>firstString(asRecord(draft.sections)[key]);
const setSection=(draft:Record<string,unknown>,key:"systemPrompt"|"developerPrompt"|"userPrompt",value:string)=>({...draft,sections:{...asRecord(draft.sections),[key]:value}});
const mapPrompt=(p:PromptRecord):FormState=>({name:p.name,slug:p.slug,description:p.description??"",categoryId:p.categoryId??"",tagIds:p.tags.map(x=>x.tag.id),draft:normalizeDraft(p.draft),variables:JSON.stringify(p.variables,null,2),metadata:JSON.stringify(p.metadata,null,2),changeSummary:""});
const parseObject=(value:string,label:string)=>{const parsed:unknown=JSON.parse(value);if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))throw new Error(`${label} must be a JSON object.`);return parsed as Record<string,unknown>};
const parseVariables=(value:string)=>{const parsed:unknown=JSON.parse(value);if(!Array.isArray(parsed))throw new Error("Variables must be a JSON array.");for(const item of parsed){if(!item||typeof item!=="object"||typeof (item as PromptVariable).name!=="string"||!["string","number","boolean","json"].includes((item as PromptVariable).type))throw new Error("Each variable requires a valid name and type.")}return parsed as PromptVariable[]};
const errorText=(e:unknown)=>e instanceof ApiError?e.message:e instanceof Error?e.message:"The prompt could not be saved.";

export function PromptCreatePage(){return <PromptForm/>} export function PromptEditPage({promptId}:{promptId:string}){return <PromptForm promptId={promptId}/>}
function PromptForm({promptId}:{promptId?:string}){
 const platform=usePlatformBootstrap(),workspaceId=platform.snapshot?.workspace.id,router=useRouter(),client=useQueryClient();
 const canRead=platform.hasPermission("prompt.library.read"),canWrite=platform.hasPermission("prompt.library.write"),canPublish=platform.hasPermission("prompt.library.publish"),canManage=platform.hasPermission("prompt.library.manage");
 const prompt=useQuery({queryKey:[...promptQueryRoot(workspaceId),"detail",promptId],queryFn:()=>getPrompt(promptId!,true),enabled:Boolean(promptId&&workspaceId&&canRead&&platform.state==="READY")});
 const categories=useQuery({queryKey:[...promptQueryRoot(workspaceId),"categories"],queryFn:listCategories,enabled:Boolean(workspaceId&&canRead&&platform.state==="READY")});
 const tags=useQuery({queryKey:[...promptQueryRoot(workspaceId),"tags"],queryFn:listTags,enabled:Boolean(workspaceId&&canRead&&platform.state==="READY")});
 const [form,setForm]=useState(empty),[baseline,setBaseline]=useState(JSON.stringify(empty)),[slugTouched,setSlugTouched]=useState(false),[failure,setFailure]=useState(""),[notice,setNotice]=useState("");
 useEffect(()=>{if(prompt.data){const next=mapPrompt(prompt.data);setForm(next);setBaseline(JSON.stringify(next));setSlugTouched(true)}},[prompt.data]);
 const dirty=JSON.stringify(form)!==baseline,readOnly=Boolean(prompt.data&&prompt.data.status!=="DRAFT");
 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault()};window.addEventListener("beforeunload",guard);return()=>window.removeEventListener("beforeunload",guard)},[dirty]);
 const payload=():PromptWriteInput=>({name:form.name.trim(),slug:form.slug,description:form.description.trim()||null,categoryId:form.categoryId||null,tagIds:form.tagIds,draft:normalizeDraft(form.draft),variables:parseVariables(form.variables),metadata:parseObject(form.metadata,"Metadata")});
 const save=useMutation({mutationFn:()=>{const input=payload();if(!promptId)return createPrompt(input);const draft={...input};delete draft.slug;return updatePrompt(promptId,draft)},onSuccess:async p=>{const next=mapPrompt(p);setForm(next);setBaseline(JSON.stringify(next));setNotice(promptId?"Prompt draft saved.":"Prompt draft created.");await client.invalidateQueries({queryKey:promptQueryRoot(workspaceId)});client.setQueryData([...promptQueryRoot(workspaceId),"detail",p.id],p);if(!promptId)router.replace(`/ai/prompts/${p.id}`)}});
 const publish=useMutation({mutationFn:()=>publishPrompt(promptId!,form.changeSummary.trim()||undefined),onSuccess:async result=>{const next=mapPrompt(result.prompt);setForm(next);setBaseline(JSON.stringify(next));setNotice("Prompt published as an immutable revision.");client.setQueryData([...promptQueryRoot(workspaceId),"detail",promptId],result.prompt);await client.invalidateQueries({queryKey:promptQueryRoot(workspaceId)})}});
 const clone=useMutation({mutationFn:()=>{const suffix=Date.now();return clonePrompt(promptId!,{name:`${prompt.data!.name} Draft`,slug:`${prompt.data!.slug}-draft-${suffix}`.slice(0,160)})},onSuccess:draft=>{router.replace(`/ai/prompts/${draft.id}`)}});
 if(platform.state==="IDLE"||platform.state==="LOADING")return <PageSkeleton rows={7}/>;
 if(platform.state==="ERROR"||!platform.snapshot)return <ErrorFallback title="Prompt editor unavailable" description="The workspace platform state could not be loaded." onRetry={platform.retry}/>;
 if(!canRead||(!promptId&&!canWrite))return <ErrorFallback title="Access denied" description={`The ${promptId?"prompt.library.read":"prompt.library.write"} permission is required.`} code={promptId?"prompt.library.read":"prompt.library.write"}/>;
 if(promptId&&prompt.isPending)return <PageSkeleton rows={7}/>;
 if(promptId&&(prompt.isError||!prompt.data))return <ErrorFallback title="Prompt unavailable" description="The requested workspace prompt could not be loaded." onRetry={()=>{void prompt.refetch()}}/>;
 const submit=async(e:FormEvent)=>{e.preventDefault();setFailure("");setNotice("");if(!form.name.trim()){setFailure("Prompt name is required.");return}if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(form.slug)){setFailure("Slug must use lowercase letters, numbers, and single hyphens.");return}try{await save.mutateAsync()}catch(e){setFailure(errorText(e))}};
 const busy=save.isPending||publish.isPending;
 return <section className="space-y-6 p-6" data-testid={promptId?"prompt-edit":"prompt-create"}><div className="flex flex-wrap justify-between gap-3"><div><Link href="/ai/prompts" className="text-sm text-muted-foreground hover:text-foreground">← Prompt Library</Link><h1 className="mt-1 text-2xl font-semibold">{promptId?form.name||"Prompt":"Create Prompt"}</h1><p className="text-sm text-muted-foreground">The draft and metadata documents follow the backend Prompt Library JSON contract.</p></div><div className="flex gap-2">{dirty&&<Badge variant="secondary">Unsaved changes</Badge>}{prompt.data&&<Badge>{prompt.data.status}</Badge>}</div></div>
  {readOnly&&<p className="rounded-md border p-3 text-sm text-muted-foreground">Published and archived prompts are immutable. Clone or restore through the supported lifecycle before creating a new editable draft.</p>}
  <form className="space-y-6" noValidate onSubmit={e=>{void submit(e)}}>
   <Card><CardHeader><CardTitle>Identity</CardTitle><CardDescription>Workspace-owned prompt identity and classification.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><Field label="Name" id="prompt-name"><Input id="prompt-name" value={form.name} maxLength={160} disabled={readOnly||busy} onChange={e=>{const name=e.target.value;setForm(s=>({...s,name,...(!slugTouched?{slug:slugify(name)}:{})}))}}/></Field><Field label="Slug" id="prompt-slug"><Input id="prompt-slug" value={form.slug} maxLength={160} disabled={Boolean(promptId)||readOnly||busy} onChange={e=>{setSlugTouched(true);setForm(s=>({...s,slug:e.target.value}))}}/></Field><Field label="Description" id="prompt-description" className="md:col-span-2"><Textarea id="prompt-description" value={form.description} maxLength={2000} disabled={readOnly||busy} onChange={e=>setForm(s=>({...s,description:e.target.value}))}/></Field><Field label="Category" id="prompt-category"><select id="prompt-category" className="h-9 w-full rounded-md border bg-background px-3 text-sm" value={form.categoryId} disabled={readOnly||busy||categories.isPending} onChange={e=>setForm(s=>({...s,categoryId:e.target.value}))}><option value="">Uncategorized</option>{(categories.data??[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><div className="space-y-2"><Label>Tags</Label><div className="flex flex-wrap gap-2">{(tags.data??[]).map(tag=><label key={tag.id} className="flex items-center gap-2 rounded-md border px-3 py-2 text-sm"><input type="checkbox" checked={form.tagIds.includes(tag.id)} disabled={readOnly||busy} onChange={e=>setForm(s=>({...s,tagIds:e.target.checked?[...s.tagIds,tag.id]:s.tagIds.filter(id=>id!==tag.id)}))}/>{tag.name}</label>)}{tags.data?.length===0&&<span className="text-sm text-muted-foreground">No tags configured.</span>}</div></div></CardContent></Card>
   <Card><CardHeader><CardTitle>Prompt document</CardTitle><CardDescription>User Prompt is required for runtime compilation. System and Developer Prompt are optional.</CardDescription></CardHeader><CardContent className="space-y-4"><Field label="System Prompt" id="prompt-system"><Textarea id="prompt-system" className="min-h-32" value={sectionValue(form.draft,"systemPrompt")} disabled={readOnly||busy} onChange={e=>setForm(s=>({...s,draft:setSection(s.draft,"systemPrompt",e.target.value)}))}/></Field><Field label="Developer Prompt" id="prompt-developer"><Textarea id="prompt-developer" className="min-h-32" value={sectionValue(form.draft,"developerPrompt")} disabled={readOnly||busy} onChange={e=>setForm(s=>({...s,draft:setSection(s.draft,"developerPrompt",e.target.value)}))}/></Field><Field label="User Prompt" id="prompt-user"><Textarea id="prompt-user" className="min-h-40" required value={sectionValue(form.draft,"userPrompt")} disabled={readOnly||busy} onChange={e=>setForm(s=>({...s,draft:setSection(s.draft,"userPrompt",e.target.value)}))}/></Field></CardContent></Card>
   <Card><CardHeader><CardTitle>Variables and metadata</CardTitle><CardDescription>Variables require name and type (string, number, boolean, or json). Published values are immutable.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><Field label="Variables JSON" id="prompt-variables"><Textarea id="prompt-variables" className="min-h-48 font-mono" value={form.variables} disabled={readOnly||busy} onChange={e=>setForm(s=>({...s,variables:e.target.value}))}/></Field><Field label="Metadata JSON" id="prompt-metadata"><Textarea id="prompt-metadata" className="min-h-48 font-mono" value={form.metadata} disabled={readOnly||busy} onChange={e=>setForm(s=>({...s,metadata:e.target.value}))}/></Field></CardContent></Card>
   {promptId&&prompt.data?.status==="DRAFT"&&canPublish&&<Card><CardHeader><CardTitle>Publish</CardTitle><CardDescription>Create an immutable published revision from the current saved draft.</CardDescription></CardHeader><CardContent><Field label="Change summary (optional)" id="prompt-change-summary"><Textarea id="prompt-change-summary" value={form.changeSummary} maxLength={1000} disabled={busy} onChange={e=>setForm(s=>({...s,changeSummary:e.target.value}))}/></Field></CardContent></Card>}
   {!canManage&&<p className="text-sm text-muted-foreground">Category and tag resource management requires prompt.library.manage.</p>}{failure&&<p role="alert" className="text-sm text-destructive">{failure}</p>}{notice&&<p role="status" className="text-sm text-green-700">{notice}</p>}
   <div className="flex flex-wrap gap-2"><Button type="submit" disabled={!canWrite||readOnly||busy}>{save.isPending?"Saving…":promptId?"Save draft":"Create prompt"}</Button>{promptId&&prompt.data?.status==="PUBLISHED"&&canWrite&&<Button type="button" variant="outline" disabled={clone.isPending} onClick={()=>{void (async()=>{setFailure("");try{await clone.mutateAsync()}catch(e){setFailure(errorText(e))}})()}}>{clone.isPending?"Creating draft…":"Edit as new draft"}</Button>}{promptId&&prompt.data?.status==="DRAFT"&&canPublish&&<Button type="button" variant="outline" disabled={dirty||busy} onClick={()=>{void (async()=>{setFailure("");try{await publish.mutateAsync()}catch(e){setFailure(errorText(e))}})()}}>{publish.isPending?"Publishing…":"Publish"}</Button>}<Button type="button" variant="ghost" disabled={!dirty||busy} onClick={()=>{const next=prompt.data?mapPrompt(prompt.data):empty;setForm(next);setBaseline(JSON.stringify(next))}}>Reset</Button></div>
  </form></section>
}
function Field({label,id,className,children}:{label:string;id:string;className?:string;children:ReactNode}){return <div className={`space-y-2 ${className??""}`}><Label htmlFor={id}>{label}</Label>{children}</div>}
