"use client";
import { useState,type FormEvent } from "react";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { Button,Card,CardContent,CardDescription,CardHeader,CardTitle,Input,Label } from "@responix/ui";
import { ApiError } from "@responix/api-client";
import { createCategory,createTag,deleteCategory,deleteTag,listCategories,listTags,promptQueryRoot,updateCategory,updateTag,type PromptNamed } from "./prompt-api";

const slugify=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,120);
const errorText=(e:unknown,fallback:string)=>e instanceof ApiError?e.message:e instanceof Error&&e.message?e.message:fallback;
export function PromptResourceManager({workspaceId}:{workspaceId:string}){
 const client=useQueryClient(),categories=useQuery({queryKey:[...promptQueryRoot(workspaceId),"categories"],queryFn:listCategories}),tags=useQuery({queryKey:[...promptQueryRoot(workspaceId),"tags"],queryFn:listTags});
 const [name,setName]=useState(""),[kind,setKind]=useState<"category"|"tag">("category"),[failure,setFailure]=useState("");
 const refresh=async()=>client.invalidateQueries({queryKey:promptQueryRoot(workspaceId)});
 const create=useMutation({mutationFn:()=>kind==="category"?createCategory(name.trim(),slugify(name)):createTag(name.trim(),slugify(name)),onSuccess:async()=>{setName("");await refresh()}});
 const remove=useMutation({mutationFn:({kind,id}:{kind:"category"|"tag";id:string})=>kind==="category"?deleteCategory(id):deleteTag(id),onSuccess:refresh});
 const rename=useMutation({mutationFn:({kind,item}:{kind:"category"|"tag";item:PromptNamed})=>{const next=window.prompt(`Rename ${kind}`,item.name)?.trim();if(!next)return Promise.resolve(item);return kind==="category"?updateCategory(item.id,next,slugify(next)):updateTag(item.id,next,slugify(next))},onSuccess:refresh});
 const runRename=async(k:"category"|"tag",item:PromptNamed)=>{setFailure("");try{await rename.mutateAsync({kind:k,item})}catch(e){setFailure(errorText(e,`The ${k} could not be renamed.`))}};
 const runRemove=async(k:"category"|"tag",item:PromptNamed)=>{setFailure("");if(!window.confirm(`Delete ${k} ${item.name}?`))return;try{await remove.mutateAsync({kind:k,id:item.id})}catch(e){setFailure(errorText(e,`The ${k} could not be deleted.`))}};
 const submit=async(e:FormEvent)=>{e.preventDefault();setFailure("");if(!name.trim())return;try{await create.mutateAsync()}catch(e){setFailure(errorText(e,`The ${kind} could not be created.`))}};
 return <Card><CardHeader><CardTitle>Categories and tags</CardTitle><CardDescription>Manage the workspace classification resources supported by Prompt Library.</CardDescription></CardHeader><CardContent className="space-y-5"><form className="flex flex-wrap items-end gap-2" onSubmit={e=>{void submit(e)}}><div className="space-y-2"><Label htmlFor="resource-kind">Resource</Label><select id="resource-kind" value={kind} onChange={e=>setKind(e.target.value as "category"|"tag")} className="h-9 rounded-md border bg-background px-3 text-sm"><option value="category">Category</option><option value="tag">Tag</option></select></div><div className="min-w-60 flex-1 space-y-2"><Label htmlFor="resource-name">Name</Label><Input id="resource-name" value={name} maxLength={120} onChange={e=>setName(e.target.value)}/></div><Button disabled={!name.trim()||create.isPending}>{create.isPending?"Adding…":"Add"}</Button></form>{failure&&<p role="alert" className="text-sm text-destructive">{failure}</p>}<div className="grid gap-4 md:grid-cols-2"><ResourceList title="Categories" kind="category" items={categories.data??[]} loading={categories.isPending} rename={item=>{void runRename("category",item)}} remove={item=>{void runRemove("category",item)}}/><ResourceList title="Tags" kind="tag" items={tags.data??[]} loading={tags.isPending} rename={item=>{void runRename("tag",item)}} remove={item=>{void runRemove("tag",item)}}/></div></CardContent></Card>
}
function ResourceList({title,kind,items,loading,rename,remove}:{title:string;kind:string;items:PromptNamed[];loading:boolean;rename:(item:PromptNamed)=>void;remove:(item:PromptNamed)=>void}){return <div className="space-y-2"><h3 className="font-medium">{title}</h3>{loading?<p className="text-sm text-muted-foreground">Loading…</p>:items.length===0?<p className="text-sm text-muted-foreground">No {kind}s configured.</p>:items.map(item=><div key={item.id} className="flex items-center justify-between gap-2 rounded-md border p-2"><div><p className="text-sm font-medium">{item.name}</p><p className="text-xs text-muted-foreground">{item.slug}</p></div><div className="flex gap-1"><Button size="sm" variant="ghost" onClick={()=>rename(item)}>Rename</Button><Button size="sm" variant="ghost" onClick={()=>remove(item)}>Delete</Button></div></div>)}</div>}