import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { PermissionDeniedError } from "@responix/api-client";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { AgentCreatePage, AgentEditPage } from "./form-page";

const baseAgent={id:"a1",workspaceId:"w1",name:"Support",slug:"support",description:"Customer support",category:"Service",status:"DRAFT",visibility:"WORKSPACE",providerId:"p1",modelId:"m1",runtimeConfiguration:{executionPipelineId:"pipe1",executionProfileId:"profile1"},temperature:0.4,topP:null,maxTokens:500,streamingEnabled:true,timeoutMs:30000,memoryEnabled:true,knowledgeEnabled:false,retrievalRuntimeId:null,toolsEnabled:true,visionEnabled:false,reasoningEnabled:false,voiceEnabled:false,imageEnabled:false,moderationEnabled:false,version:1,promptBindings:[{role:"SYSTEM",promptId:"pr1"}],createdAt:"2026-01-01",updatedAt:"2026-01-01"};
const provider={id:"p1",providerName:"OpenAI",status:"ACTIVE",configured:true,providerConfigurationId:"pc1",enabled:true,models:[{modelId:"m1",modelName:"gpt",displayName:"GPT",status:"ACTIVE",contextWindow:10000,maxOutputTokens:2000,supportsVision:true,supportsAudio:false,supportsTools:true,supportsReasoning:true,supportsStreaming:true}]};
interface FormMocks { platform:{state:string;snapshot:{workspace:{id:string}}|null;retry:ReturnType<typeof vi.fn>;hasPermission:ReturnType<typeof vi.fn<(permission:string)=>boolean>>};replace:ReturnType<typeof vi.fn>;invalidate:ReturnType<typeof vi.fn>;setData:ReturnType<typeof vi.fn>;queryConfigs:Array<{queryKey:unknown[]}>;agentData:unknown;save:ReturnType<typeof vi.fn<(input:unknown)=>Promise<unknown>>>;publish:ReturnType<typeof vi.fn<()=>Promise<unknown>>>;clone:ReturnType<typeof vi.fn<(id:string,input:unknown)=>Promise<unknown>>> }
const mocks=vi.hoisted(():FormMocks=>({platform:{state:"READY",snapshot:{workspace:{id:"w1"}},retry:vi.fn(),hasPermission:vi.fn((permission:string)=>Boolean(permission))},replace:vi.fn(),invalidate:vi.fn(),setData:vi.fn(),queryConfigs:[],agentData:undefined,save:vi.fn(),publish:vi.fn(),clone:vi.fn()}));
vi.mock("next/navigation",()=>({useRouter:()=>({replace:mocks.replace})}));
vi.mock("../../platform",()=>({usePlatformBootstrap:()=>mocks.platform}));
vi.mock("@tanstack/react-query",()=>({
  useQuery:(config:{queryKey:unknown[]})=>{mocks.queryConfigs.push(config);const key=config.queryKey;if(key[2]==="agent")return {data:mocks.agentData,isPending:false,isError:false,refetch:vi.fn()};if(key[2]==="ai-providers")return {data:[provider],isPending:false,isError:false};return {data:{data:[{id:"pr1",name:"Support Prompt",slug:"support",description:null,status:"PUBLISHED",revision:1,draft:{sections:{userPrompt:"User"}}},{id:"invalid",name:"Legacy Prompt",slug:"legacy",description:null,status:"PUBLISHED",revision:1,draft:{system_prompt:"System only"}}]},isPending:false,isError:false}},
  useMutation:(config:{mutationFn:()=>Promise<unknown>;onSuccess:(value:never)=>Promise<void>})=>({isPending:false,mutateAsync:async()=>{const value=await config.mutationFn();await config.onSuccess(value as never);return value}}),
  useQueryClient:()=>({invalidateQueries:mocks.invalidate,setQueryData:mocks.setData})
}));
vi.mock("./agent-api",()=>({getAgent:vi.fn(()=>Promise.resolve(mocks.agentData)),listProviders:vi.fn(()=>Promise.resolve([provider])),listPrompts:vi.fn(()=>Promise.resolve({data:[]})),listExecutionPipelines:vi.fn(()=>Promise.resolve({data:[]})),listExecutionProfiles:vi.fn(()=>Promise.resolve({data:[]})),createAgent:(input:unknown):Promise<unknown>=>mocks.save(input),updateAgent:(_id:string,input:unknown):Promise<unknown>=>mocks.save(input),publishAgent:():Promise<unknown>=>mocks.publish(),cloneAgent:(id:string,input:unknown):Promise<unknown>=>mocks.clone(id,input)}));

function fillRequired(){fireEvent.change(screen.getByLabelText("Name"),{target:{value:"Sales Agent"}});fireEvent.change(screen.getByLabelText("Provider"),{target:{value:"p1"}});fireEvent.change(screen.getByLabelText("Model"),{target:{value:"m1"}})}

describe("Agent configuration",()=>{
  beforeEach(()=>{mocks.platform.state="READY";mocks.platform.snapshot={workspace:{id:"w1"}};mocks.platform.hasPermission.mockReturnValue(true);mocks.agentData=undefined;mocks.save.mockReset();mocks.publish.mockReset();mocks.clone.mockReset();mocks.replace.mockReset();mocks.invalidate.mockReset().mockResolvedValue(undefined);mocks.setData.mockReset();mocks.queryConfigs.length=0});
  it("validates required fields without invoking the API",()=>{render(<AgentCreatePage/>);fireEvent.click(screen.getByRole("button",{name:"Create agent"}));expect(screen.getByRole("alert")).toHaveTextContent("Agent name is required");expect(mocks.save).not.toHaveBeenCalled()});
  it("creates with authoritative provider/model and prompt fields",async()=>{mocks.save.mockResolvedValue(baseAgent);render(<AgentCreatePage/>);fillRequired();fireEvent.change(screen.getByLabelText("System prompt"),{target:{value:"pr1"}});fireEvent.click(screen.getByRole("button",{name:"Create agent"}));await waitFor(()=>expect(mocks.save).toHaveBeenCalled());expect(mocks.save.mock.calls[0]?.[0]).toMatchObject({name:"Sales Agent",slug:"sales-agent",configuration:{providerId:"p1",modelId:"m1",providerConfigurationId:"pc1"},promptBindings:[{role:"SYSTEM",promptId:"pr1"}]});expect(mocks.replace).toHaveBeenCalledWith("/ai/agents/a1")});
  it("does not offer an invalid published Prompt and identifies an existing invalid binding",()=>{const invalidAgent={...baseAgent,promptBindings:[{role:"SYSTEM",promptId:"invalid"}]};const createView=render(<AgentCreatePage/>);expect(screen.getByLabelText<HTMLSelectElement>("System prompt").querySelector('option[value="invalid"]')).toBeNull();createView.unmount();mocks.agentData=invalidAgent;render(<AgentEditPage agentId="a1"/>);const invalidOption=screen.getByLabelText<HTMLSelectElement>("System prompt").querySelector('option[value="invalid"]');expect(invalidOption).toBeDisabled();expect(invalidOption).toHaveTextContent("Invalid: USER_PROMPT_MISSING");expect(screen.getByRole("alert")).toHaveTextContent("sections.userPrompt")});
  it("surfaces API validation failures",async()=>{mocks.save.mockRejectedValue(new Error("server rejected"));render(<AgentCreatePage/>);fillRequired();fireEvent.click(screen.getByRole("button",{name:"Create agent"}));await waitFor(()=>expect(screen.getByRole("alert")).toHaveTextContent("could not be saved"))});
  it("surfaces backend authorization failures",async()=>{mocks.save.mockRejectedValue(new PermissionDeniedError("Agent creation is forbidden"));render(<AgentCreatePage/>);fillRequired();fireEvent.click(screen.getByRole("button",{name:"Create agent"}));await waitFor(()=>expect(screen.getByRole("alert")).toHaveTextContent("Agent creation is forbidden"))});
  it("loads persisted values and updates using workspace-scoped cache keys",async()=>{mocks.agentData=baseAgent;mocks.save.mockResolvedValue({...baseAgent,description:"Updated"});render(<AgentEditPage agentId="a1"/>);expect(screen.getByLabelText<HTMLInputElement>("Name").value).toBe("Support");expect(screen.getByLabelText<HTMLSelectElement>("Model").value).toBe("m1");expect(mocks.queryConfigs.some((q)=>JSON.stringify(q.queryKey)===JSON.stringify(["workspace","w1","agent","a1"]))).toBe(true);fireEvent.change(screen.getByLabelText("Description"),{target:{value:"Updated"}});fireEvent.click(screen.getByRole("button",{name:"Save changes"}));await waitFor(()=>expect(mocks.save).toHaveBeenCalledWith(expect.objectContaining({description:"Updated"})));expect(mocks.invalidate).toHaveBeenCalledWith({queryKey:["workspace","w1","agents"]})});
  it("opens a supported editable draft for a published Agent",async()=>{mocks.agentData={...baseAgent,status:"PUBLISHED"};mocks.clone.mockResolvedValue({...baseAgent,id:"draft-copy",status:"DRAFT"});render(<AgentEditPage agentId="a1"/>);fireEvent.click(screen.getByRole("button",{name:"Edit as new draft"}));await waitFor(()=>expect(mocks.clone).toHaveBeenCalledWith("a1",expect.objectContaining({name:"Support Draft"})));expect(mocks.replace).toHaveBeenCalledWith("/ai/agents/draft-copy")});
  it("denies create access without write permission",()=>{mocks.platform.hasPermission.mockImplementation((p:string)=>p!=="agent.studio.write");render(<AgentCreatePage/>);expect(screen.getByText("Access denied")).toBeInTheDocument();expect(screen.queryByTestId("agent-create")).not.toBeInTheDocument()});
});
