function addCurrentTagsData(t,a){}function editCurrentTagsData(t,e){return $("#"+t+" .tagify__tag").each(function(t,a){e.base.taglist.push({id:$(a).attr("tags-id"),tagname:$(a).attr("value")})}),e}function throttle(l,d,t={leading:!0,trailing:!1}){let o=0,g=null;const{leading:c,trailing:r,resultCallback:u}=t;function a(...n){return new Promise((a,t)=>{var e,s=(new Date).getTime(),i=(o||c||(o=s),d-(s-o));i<=0?(g&&(clearTimeout(g),g=null),e=l.apply(this,n),u&&u(e),a(e),o=s):r&&!g&&(g=setTimeout(()=>{g=null,o=c?(new Date).getTime():0;var t=l.apply(this,n);u&&u(t),a(t)},i))})}return a.cancel=function(){g&&clearTimeout(g),g=null,o=0},a}function tagsAddButtonClick(t){10<=$("#"+t+" .tagify__tag").length?$("#"+t+" .tags-add").attr("disabled","disabled"):$("#"+t+" .tags-add").removeAttr("disabled")}function tagsPopupPasteEvent(){$(".tagify__tag").each(function(){try{document.execCommand("AutoUrlDetect",!1,!1)}catch(t){}$(this).on("paste",function(t){t.preventDefault();var a,e=null;e=(e=(e=(e=window.clipboardData&&clipboardData.setData?window.clipboardData.getData("text"):(t.originalEvent||t).clipboardData.getData("text/plain"))&&e.replaceAll("\n"," "))&&e.replaceAll("\r",""))&&e.substring(0,60),document.body.createTextRange?(document.selection?textRange=document.selection.createRange():window.getSelection&&(t=(sel=window.getSelection()).getRangeAt(0),(a=document.createElement("span")).innerHTML="&#FEFF;",t.deleteContents(),t.insertNode(a),(textRange=document.body.createTextRange()).moveToElementText(a),a.parentNode.removeChild(a)),textRange.text=e,textRange.collapse(!1),textRange.select()):document.execCommand("insertText",!1,e)})})}function tagsPopupCheck(t,a){"offcanvasAdd"==t?(_ad=$("#offcanvasAdd").attr("controls-id"),addeidtValidateCurrentDate("#offcanvasAdd",parseInt(_ad),a)):(_ed=registeredPages[$("#"+t).attr("data-controls").toLowerCase()],addeidtValidateCurrentDate("#"+t,_ed,a))}let initTagData=[];async function initTagify(l,d){try{var o=await handle.sendMessage("GET_TAGES",{});if(0<o.length)for(var g in initTagData.length=0,o)isBlank(o[g].tagname)||initTagData.push({id:o[g].id,value:o[g].tagname,createDate:o[g].createDate,useDate:o[g].useDate});var c=$$(l).querySelector("input.tags-input");c.tagify&&c.tagify.destroy(),c.value="";let a=c.tagify=new Tagify(c,{whitelist:initTagData,tagTextProp:"value",dropdown:{position:"input",maxItems:1e3,enabled:0,classname:"sugtagList",appendTarget:c.parentNode},userInput:!0,duplicates:!1,templates:{tag(t,{settings:a}){var e=findTagByName(initTagData,t.value),e=(e&&(t.id=e),tagid2pic(t.id));return`
                        <tag title="${285<parseInt(t.value.pxWidth(14))?t.value:""}"
                                contenteditable='false'
                                spellcheck='false'
                                tabIndex="${a.a11y.focusableTags?0:-1}"
                                class="${a.classNames.tag} ${t.class||""} tag${e}"
                                tags-id = '${t.id}'
                                ${this.getAttributes(t)}>
                            <x title='${getMessage("remove")}' class="${a.classNames.tagX}" role='button' aria-label='remove tag'></x>
                            <div>
                                <div class="tag-icon"><svg class="new-svg tag-icon${e} small"><use xlink:href="#ico_tag_small"></use></svg></div>
                                <span style = "min-width:36px;" class="tag-text tagify__tag-text">${t[a.tagTextProp]||t.value}</span>
                            </div>
                        </tag>
                    `},dropdownItem(t){var a=tagid2pic(t.id);return`
                        <div  ${this.getAttributes(t)}
                                class='${this.settings.classNames.dropdownItem} ${t.class||""} tag${a}'
                                tabindex="0"
                                 tags-id = '${t.id}'
                                 role="option" 
                                 data-value = '${t.value}'>
                            <div class="allitem-icon"><svg class="new-svg tag-icon${a} small"><use xlink:href="#ico_tag_small"></use></svg></div>
                            <div class="allitem-desc" title="${240<Math.ceil(t.value.pxWidth(14))?t.value:""}">
                                <span class="allitemTitleText tag-text">${t.value}</span>
                            </div>
                        </div>
                    `}},enforceWhitelist:!1,editTags:{clicks:2,keepInvalid:!1},callbacks:{},placeholder:""});var r=[];if("offcanvasAdd"!=l||"confirm-container"!=l){"offcanvasView"==l||"offcanvasViewRecycle"==l?$(".tags-add").css("display","none"):$(".tags-add").css("display","flex");var u=$("#"+l).attr("controls-id"),p=await handle.sendMessage("GET_ITEMTAGS",{id:u});if(0<p.length){for(var f in p)isBlank(p[f].tagname)||r.push({id:p[f].id,value:p[f].tagname});a.addTags(r),"offcanvasView"!=l&&"offcanvasViewRecycle"!=l||(0<r.length?$("#"+l+" .from-tags-label").css("display","flex"):$("#"+l+" .from-tags-label").css("display","none"),$("#"+l+" .tagify__tag").css("pointer-events","auto"),$("#"+l+" .tagify").css("pointer-events","auto"),$("#"+l+" .tagify__tag__removeBtn").css("display","none"),$(".tag-text").css("margin-right","6px")),"confirm-container"!=l&&$("#"+l+" .from-tags").attr("data-length",r.length)}else"offcanvasView"!=l&&"offcanvasViewRecycle"!=l||$("#"+l+" .from-tags-label").css("display","none")}else $(".tags-add").css("display","flex");let t,e="",s=[],i,n;tagsAddButtonClick(l),t="#"+l,"offcanvasAdd"==l&&"tags-panel"==$("#addListButton").attr("data-controls")&&(i=$("#options-tab .options-item.tagsitem.selected").attr("data-anchor"),n=$("#options-tab .options-item.tagsitem.selected").find(".allitemTitleText").html(),(s=[]).push({id:i,value:n}),a.addTags(s),1!=$("#offcanvasAdd").attr("controls-id")||1==$("#offcanvasAdd").attr("controls-id"))&&addeidtValidateCurrentDisabled(!0,t,!0);getMessage("new_tag"),$$(l).querySelector(".tags-add").addEventListener("click",function(t){a.addEmptyTag({tagname:"",id:guid()}),a.updateValueByDOMTags(),a.dropdown.show(),a.on("edit:updated",async t=>{tagsAddButtonClick(l),e=t.detail.tag.__tagifyTagData.id,$("#"+e).removeClass("tagedit"),tagsPopupCheck(l,d)}),a.on("edit:input",throttle(t=>{e=t.detail.tag.__tagifyTagData.id,$("#"+e).addClass("tagedit")},500,{leading:!0,trailing:!0})),tagsPopupPasteEvent()}),a.on("change",async t=>{tagsPopupCheck(l,d),tagsAddButtonClick(l)});a.on("remove",async t=>{a.dropdown.hide(),tagsAddButtonClick(l),tagsPopupCheck(l,d)})}catch(t){}}