/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import { BadRequestException } from "@nestjs/common";
import { ProviderManagementService } from "./provider-management.service";

const state={providerId:"p1",providerName:"OpenAI",configured:true,enabled:true,credentialConfigured:true,settings:{},updatedAt:new Date("2026-01-01T00:00:00Z")};
describe("ProviderManagementService",()=>{
 const repository={getSafe:jest.fn(),configure:jest.fn(),validationTarget:jest.fn(),recordValidation:jest.fn()};
 const credentials={useCredential:jest.fn()};const registry={has:jest.fn(),get:jest.fn()};const destinations={authorize:jest.fn()};
 const service=new ProviderManagementService(repository as never,credentials as never,registry as never,destinations as never);
 beforeEach(()=>{jest.clearAllMocks();repository.getSafe.mockResolvedValue(state);repository.configure.mockResolvedValue(state);registry.has.mockReturnValue(true);destinations.authorize.mockResolvedValue({})});
 it("normalizes safe settings and passes write-only credentials",async()=>{await service.configure("w1","u1","p1",{enabled:true,settings:{apiBaseUrl:"https://api.openai.com/v1/"},credential:{name:"primary",secret:"secret-value"}});expect(repository.configure).toHaveBeenCalledWith(expect.objectContaining({workspaceId:"w1",actorId:"u1",providerId:"p1",settings:{apiBaseUrl:"https://api.openai.com/v1"},credential:{name:"primary",secret:"secret-value"}}));expect(await service.get("w1","p1")).not.toHaveProperty("secret")});
 it("preserves credentials when omitted",async()=>{await service.configure("w1","u1","p1",{enabled:false});expect(repository.configure).toHaveBeenCalledWith(expect.not.objectContaining({credential:expect.anything()}))});
 it("rejects unsupported adapters and unsafe endpoints",async()=>{registry.has.mockReturnValue(false);await expect(service.configure("w1","u1","p1",{enabled:true})).rejects.toBeInstanceOf(BadRequestException);registry.has.mockReturnValue(true);destinations.authorize.mockRejectedValue(Object.assign(new Error(),{name:"ProviderDestinationRejectedError"}))});
 it("validates through the registered adapter and stores only safe health",async()=>{repository.validationTarget.mockResolvedValue({providerId:"p1",providerName:"OpenAI",modelId:"m1",modelName:"gpt",apiBaseUrl:null,maxOutputTokens:8});const invoke=jest.fn().mockResolvedValue({});registry.get.mockReturnValue({invoke});credentials.useCredential.mockImplementation(async(_w:string,_p:string,operation:(c:{id:string;secret:string})=>Promise<void>)=>operation({id:"c1",secret:"plain"}));repository.recordValidation.mockResolvedValue({checkedAt:new Date("2026-01-01T00:00:00Z")});const result=await service.validate("w1","u1","p1");expect(result.available).toBe(true);expect(repository.recordValidation).toHaveBeenCalledWith(expect.objectContaining({workspaceId:"w1",actorId:"u1",available:true}));expect(JSON.stringify(repository.recordValidation.mock.calls)).not.toContain("plain")});
 it("returns a redacted validation failure",async()=>{repository.validationTarget.mockResolvedValue({providerId:"p1",providerName:"OpenAI",modelId:"m1",modelName:"gpt",apiBaseUrl:null,maxOutputTokens:8});registry.get.mockReturnValue({invoke:jest.fn()});credentials.useCredential.mockRejectedValue({code:"AUTHENTICATION_FAILED",message:"secret-value"});repository.recordValidation.mockResolvedValue({checkedAt:new Date("2026-01-01T00:00:00Z")});await expect(service.validate("w1","u1","p1")).resolves.toMatchObject({available:false,errorCode:"AUTHENTICATION_FAILED"});expect(JSON.stringify(repository.recordValidation.mock.calls)).not.toContain("secret-value")});
});
